// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
  TypeBuilder as __TypeBuilder,
  t as __t,
} from "spacetimedb";

export default {
  accountId: __t.u64(),
  newName: __t.string(),
  newSubAccountType: __t.string(),
  newCreditLimitCentavos: __t.i64(),
  existingName: __t.string(),
  existingSubAccountType: __t.string(),
};
