// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
	type AlgebraicTypeType as __AlgebraicTypeType,
	type Infer as __Infer,
	TypeBuilder as __TypeBuilder,
	t as __t,
} from "spacetimedb";

export default {
	name: __t.string(),
	type: __t.string(),
	amountCentavos: __t.i64(),
	tag: __t.string(),
	subAccountId: __t.u64(),
	dayOfMonth: __t.u8(),
	remainingMonths: __t.u16(),
	totalMonths: __t.u16(),
};
