// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
  TypeBuilder as __TypeBuilder,
  t as __t,
} from "spacetimedb";

export default {
  personName: __t.string(),
  direction: __t.string(),
  amountCentavos: __t.i64(),
  subAccountId: __t.u64(),
  tag: __t.string(),
  description: __t.string(),
  date: __t.timestamp(),
};
