// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
  TypeBuilder as __TypeBuilder,
  t as __t,
} from "spacetimedb";

export default {
  description: __t.string(),
  totalAmountCentavos: __t.i64(),
  payerSubAccountId: __t.u64(),
  tag: __t.string(),
  date: __t.timestamp(),
  participantNames: __t.array(__t.string()),
};
