// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  splitEventId: __t.u64(),
  description: __t.string(),
  totalAmountCentavos: __t.i64(),
  payerSubAccountId: __t.u64(),
  tag: __t.string(),
  date: __t.timestamp(),
  splitMethod: __t.string(),
  participantIds: __t.array(__t.u64()),
  participantNames: __t.array(__t.string()),
  participantShares: __t.array(__t.i64()),
  participantShareCounts: __t.array(__t.u32()),
};
