// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64(),
  ownerIdentity: __t.identity().name("owner_identity"),
  name: __t.string(),
  isStandalone: __t.bool().name("is_standalone"),
  createdAt: __t.timestamp().name("created_at"),
  iconBankId: __t.option(__t.string()).name("icon_bank_id"),
});
