// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
	type AlgebraicTypeType as __AlgebraicTypeType,
	type Infer as __Infer,
	TypeBuilder as __TypeBuilder,
	t as __t,
} from "spacetimedb";

export default __t.row({
	id: __t.u64(),
	ownerIdentity: __t.identity().name("owner_identity"),
	description: __t.string(),
	totalAmountCentavos: __t.i64().name("total_amount_centavos"),
	payerSubAccountId: __t.u64().name("payer_sub_account_id"),
	tag: __t.string(),
	date: __t.timestamp(),
	createdAt: __t.timestamp().name("created_at"),
});
