// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  subAccountId: __t.u64().name("sub_account_id"),
  ownerIdentity: __t.identity().name("owner_identity"),
  interestRateBps: __t.u32().name("interest_rate_bps"),
  maturityDate: __t.timestamp().name("maturity_date"),
  recurringDefinitionId: __t.u64().name("recurring_definition_id"),
  isMatured: __t.bool().name("is_matured"),
  principalCentavos: __t.i64().name("principal_centavos"),
  createdAt: __t.timestamp().name("created_at"),
});
