// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import type { Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import type AddCustomTagReducer from "../add_custom_tag_reducer";
import type AddSubAccountReducer from "../add_sub_account_reducer";
import type ConvertAndCreateSubAccountReducer from "../convert_and_create_sub_account_reducer";
import type CreateAccountReducer from "../create_account_reducer";
import type CreateDebtReducer from "../create_debt_reducer";
import type CreateRecurringDefinitionReducer from "../create_recurring_definition_reducer";
import type CreateSplitReducer from "../create_split_reducer";
import type CreateTransactionReducer from "../create_transaction_reducer";
import type DeleteAccountReducer from "../delete_account_reducer";
import type DeleteCustomTagReducer from "../delete_custom_tag_reducer";
import type DeleteDebtReducer from "../delete_debt_reducer";
import type DeleteRecurringDefinitionReducer from "../delete_recurring_definition_reducer";
import type DeleteSplitReducer from "../delete_split_reducer";
import type DeleteSubAccountReducer from "../delete_sub_account_reducer";
import type DeleteTransactionReducer from "../delete_transaction_reducer";
import type EditRecurringDefinitionReducer from "../edit_recurring_definition_reducer";
import type EditSubAccountReducer from "../edit_sub_account_reducer";
import type EditTransactionReducer from "../edit_transaction_reducer";
import type LinkClerkIdentityReducer from "../link_clerk_identity_reducer";
import type PauseRecurringDefinitionReducer from "../pause_recurring_definition_reducer";
import type RenameAccountReducer from "../rename_account_reducer";
import type RenameSubAccountReducer from "../rename_sub_account_reducer";
import type ResumeRecurringDefinitionReducer from "../resume_recurring_definition_reducer";
import type SetBudgetAllocationsReducer from "../set_budget_allocations_reducer";
import type SetBudgetReducer from "../set_budget_reducer";
import type SettleDebtReducer from "../settle_debt_reducer";
import type ToggleTagVisibilityReducer from "../toggle_tag_visibility_reducer";
import type UpdateAccountIconReducer from "../update_account_icon_reducer";

export type AddCustomTagParams = __Infer<typeof AddCustomTagReducer>;
export type AddSubAccountParams = __Infer<typeof AddSubAccountReducer>;
export type ConvertAndCreateSubAccountParams = __Infer<typeof ConvertAndCreateSubAccountReducer>;
export type CreateAccountParams = __Infer<typeof CreateAccountReducer>;
export type CreateDebtParams = __Infer<typeof CreateDebtReducer>;
export type CreateRecurringDefinitionParams = __Infer<typeof CreateRecurringDefinitionReducer>;
export type CreateSplitParams = __Infer<typeof CreateSplitReducer>;
export type CreateTransactionParams = __Infer<typeof CreateTransactionReducer>;
export type DeleteAccountParams = __Infer<typeof DeleteAccountReducer>;
export type DeleteCustomTagParams = __Infer<typeof DeleteCustomTagReducer>;
export type DeleteDebtParams = __Infer<typeof DeleteDebtReducer>;
export type DeleteRecurringDefinitionParams = __Infer<typeof DeleteRecurringDefinitionReducer>;
export type DeleteSplitParams = __Infer<typeof DeleteSplitReducer>;
export type DeleteSubAccountParams = __Infer<typeof DeleteSubAccountReducer>;
export type DeleteTransactionParams = __Infer<typeof DeleteTransactionReducer>;
export type EditRecurringDefinitionParams = __Infer<typeof EditRecurringDefinitionReducer>;
export type EditSubAccountParams = __Infer<typeof EditSubAccountReducer>;
export type EditTransactionParams = __Infer<typeof EditTransactionReducer>;
export type LinkClerkIdentityParams = __Infer<typeof LinkClerkIdentityReducer>;
export type PauseRecurringDefinitionParams = __Infer<typeof PauseRecurringDefinitionReducer>;
export type RenameAccountParams = __Infer<typeof RenameAccountReducer>;
export type RenameSubAccountParams = __Infer<typeof RenameSubAccountReducer>;
export type ResumeRecurringDefinitionParams = __Infer<typeof ResumeRecurringDefinitionReducer>;
export type SetBudgetParams = __Infer<typeof SetBudgetReducer>;
export type SetBudgetAllocationsParams = __Infer<typeof SetBudgetAllocationsReducer>;
export type SettleDebtParams = __Infer<typeof SettleDebtReducer>;
export type ToggleTagVisibilityParams = __Infer<typeof ToggleTagVisibilityReducer>;
export type UpdateAccountIconParams = __Infer<typeof UpdateAccountIconReducer>;
