// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddCustomTagReducer from "../add_custom_tag_reducer";
import AddSubAccountReducer from "../add_sub_account_reducer";
import ConvertAndCreateSubAccountReducer from "../convert_and_create_sub_account_reducer";
import CreateAccountReducer from "../create_account_reducer";
import CreateDebtReducer from "../create_debt_reducer";
import CreateRecurringDefinitionReducer from "../create_recurring_definition_reducer";
import CreateSplitReducer from "../create_split_reducer";
import CreateTransactionReducer from "../create_transaction_reducer";
import DeleteAccountReducer from "../delete_account_reducer";
import DeleteCustomTagReducer from "../delete_custom_tag_reducer";
import DeleteDebtReducer from "../delete_debt_reducer";
import DeleteRecurringDefinitionReducer from "../delete_recurring_definition_reducer";
import DeleteSplitReducer from "../delete_split_reducer";
import DeleteSubAccountReducer from "../delete_sub_account_reducer";
import DeleteTransactionReducer from "../delete_transaction_reducer";
import EditRecurringDefinitionReducer from "../edit_recurring_definition_reducer";
import EditSubAccountReducer from "../edit_sub_account_reducer";
import EditTransactionReducer from "../edit_transaction_reducer";
import LinkClerkIdentityReducer from "../link_clerk_identity_reducer";
import MigrateRecurringToV2Reducer from "../migrate_recurring_to_v_2_reducer";
import PauseRecurringDefinitionReducer from "../pause_recurring_definition_reducer";
import RenameAccountReducer from "../rename_account_reducer";
import RenameSubAccountReducer from "../rename_sub_account_reducer";
import ResumeRecurringDefinitionReducer from "../resume_recurring_definition_reducer";
import SetBudgetReducer from "../set_budget_reducer";
import SetBudgetAllocationsReducer from "../set_budget_allocations_reducer";
import SettleDebtReducer from "../settle_debt_reducer";
import ToggleTagVisibilityReducer from "../toggle_tag_visibility_reducer";
import UpdateAccountIconReducer from "../update_account_icon_reducer";

export type AddCustomTagParams = __Infer<typeof AddCustomTagReducer>;
export type AddSubAccountParams = __Infer<typeof AddSubAccountReducer>;
export type ConvertAndCreateSubAccountParams = __Infer<typeof ConvertAndCreateSubAccountReducer>;
export type CreateAccountParams = __Infer<typeof CreateAccountReducer>;
export type CreateDebtParams = __Infer<typeof CreateDebtReducer>;
export type CreateRecurringDefinitionParams = __Infer<typeof CreateRecurringDefinitionReducer>;
export type CreateSplitParams = __Infer<typeof CreateSplitReducer>;
export type CreateTransactionParams = __Infer<typeof CreateTransactionReducer>;
export type DeleteAccountParams = __Infer<typeof DeleteAccountReducer>;
export type DeleteCustomTagParams = __Infer<typeof DeleteCustomTagReducer>;
export type DeleteDebtParams = __Infer<typeof DeleteDebtReducer>;
export type DeleteRecurringDefinitionParams = __Infer<typeof DeleteRecurringDefinitionReducer>;
export type DeleteSplitParams = __Infer<typeof DeleteSplitReducer>;
export type DeleteSubAccountParams = __Infer<typeof DeleteSubAccountReducer>;
export type DeleteTransactionParams = __Infer<typeof DeleteTransactionReducer>;
export type EditRecurringDefinitionParams = __Infer<typeof EditRecurringDefinitionReducer>;
export type EditSubAccountParams = __Infer<typeof EditSubAccountReducer>;
export type EditTransactionParams = __Infer<typeof EditTransactionReducer>;
export type LinkClerkIdentityParams = __Infer<typeof LinkClerkIdentityReducer>;
export type MigrateRecurringToV2Params = __Infer<typeof MigrateRecurringToV2Reducer>;
export type PauseRecurringDefinitionParams = __Infer<typeof PauseRecurringDefinitionReducer>;
export type RenameAccountParams = __Infer<typeof RenameAccountReducer>;
export type RenameSubAccountParams = __Infer<typeof RenameSubAccountReducer>;
export type ResumeRecurringDefinitionParams = __Infer<typeof ResumeRecurringDefinitionReducer>;
export type SetBudgetParams = __Infer<typeof SetBudgetReducer>;
export type SetBudgetAllocationsParams = __Infer<typeof SetBudgetAllocationsReducer>;
export type SettleDebtParams = __Infer<typeof SettleDebtReducer>;
export type ToggleTagVisibilityParams = __Infer<typeof ToggleTagVisibilityReducer>;
export type UpdateAccountIconParams = __Infer<typeof UpdateAccountIconReducer>;

